const OPEN_DRAWER = 'OPEN_DRAWER';
const CLOSE_DRAWER = 'CLOSE_DRAWER';
const OPEN_PROFILE = 'OPEN_PROFILE';
const CLOSE_PROFILE = 'CLOSE_PROFILE';

export { OPEN_DRAWER, CLOSE_DRAWER, OPEN_PROFILE, CLOSE_PROFILE };
